version: 2
updates:  
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Australia/Melbourne
  open-pull-requests-limit: 100
  reviewers:
  - Chii-Onan
  assignees:
  - Chii-Onan
