namespace Ayano.Plugins.Fun.Services;

public class Utils
{
    public static string[] education =
    {
        "High School",
        "College",
        "Middle School",
        "Elementary School",
        "Pre School",
        "Retard never went to school LOL",
        "NASA",
        "Drug Dealer"
    };

    public static string[] email =
    {
        "@gmail.com",
        "@yahoo.com",
        "@hotmail.com",
        "@outlook.com",
        "@protonmail.com",
        "@disposablemail.com",
        "@aol.com",
        "@edu.com",
        "@icloud.com",
        "@gmx.net",
        "@yandex.com",
        "@retard.ed"
    };

    public static string[] ethnicity =
    {
        "White",
        "African American",
        "Asian",
        "THICC Latino",
        "Latina",
        "American",
        "Mexican",
        "Korean",
        "Chinese",
        "Lithuanian",
        "Romanian",
        "Bulgarian",
        "Spaniard",
        "Sexy Arab",
        "Italian",
        "Puerto Rican",
        "Non-Hispanic",
        "Russian",
        "Canadian",
        "European",
        "Indian",
        "CHAD bengali",
        "Terrorist",
        "Indian"
    };

    public static string[] hair_color =
    {
        "Black",
        "Brown",
        "Blonde",
        "White",
        "Gray",
        "Red",
        "Blue"
    };

    public static string[] likes =
    {
        "Gaming",
        "Being a dickhead",
        "Being a bitch",
        "Being cringe",
        "Killing Fags",
        "Being Narcissistic",
        "Living in his mom's basement",
        "Food",
        "Really likes food",
        "Poop",
        "Scat",
        "Sounding",
        "My Little Pony"
    };

    public static string[] location =
    {
        "Retard lives in his mom's basement LOL",
        "America",
        "United States",
        "Europe",
        "Poland",
        "Mexico",
        "Russia",
        "Pakistan",
        "India",
        "Philippines",
        "Taiwan",
        "China",
        "Japan",
        "North Korea",
        "South Korea",
        "Some random third world country",
        "Canada",
        "Alabama",
        "Alaska",
        "Arizona",
        "Arkansas",
        "California",
        "Colorado",
        "Connecticut",
        "Delaware",
        "Florida",
        "Georgia",
        "Hawaii",
        "Idaho",
        "Illinois",
        "Indiana",
        "Iowa",
        "Kansas",
        "Kentucky",
        "Louisiana",
        "Maine",
        "Maryland",
        "Massachusetts",
        "Michigan",
        "Minnesota",
        "Mississippi",
        "Missouri",
        "Montana",
        "Nebraska",
        "Nevada",
        "New Hampshire",
        "New Jersey",
        "New Mexico",
        "New York",
        "North Carolina",
        "North Dakota",
        "Ohio",
        "Oklahoma",
        "Oregon",
        "Pennsylvania",
        "Rhode Island",
        "South Carolina",
        "South Dakota",
        "Tennessee",
        "Texas",
        "Utah",
        "Vermont",
        "Virginia",
        "Washington",
        "West Virginia",
        "Wisconsin",
        "Wyoming",
        "In your MOM",
        "Cumming",
        "Spain",
        "COUNTRY WITH BOOM BOOM STICK",
        "BANGLADESH",
        "In the SEA",
        "No home",
        "Gypsy",
        "Homeless fag",
        "Iceland",
        "Greenland",
        "Germany",
        "France",
        "Spain",
        "Portugal"
    };

    public static string[] name =
    {
        "James Smith",
        "Michael Smith",
        "Robert Smith",
        "Maria Garcia",
        "David Smith",
        "Maria Rodriguez",
        "Mary Smith",
        "Maria Hernandez",
        "Maria Martinez",
        "James Johnson",
        "Catherine Smoaks",
        "Cindi Emerick",
        "Trudie Peasley",
        "Josie Dowler",
        "Jefferey Amon",
        "Kyung Kernan",
        "Lola Barreiro",
        "Barabara Nuss",
        "Lien Barmore",
        "Donnell Kuhlmann",
        "Geoffrey Torre",
        "Allan Craft",
        "Elvira Lucien",
        "Jeanelle Orem",
        "Shantelle Lige",
        "Chassidy Reinhardt",
        "Adam Delange",
        "Anabel Rini",
        "Delbert Kruse",
        "Celeste Baumeister",
        "Jon Flanary",
        "Danette Uhler",
        "Xochitl Parton",
        "Derek Hetrick",
        "Chasity Hedge",
        "Antonia Gonsoulin",
        "Tod Kinkead",
        "Chastity Lazar",
        "Jazmin Aumick",
        "Janet Slusser",
        "Junita Cagle",
        "Stepanie Blandford",
        "Lang Schaff",
        "Kaila Bier",
        "Ezra Battey",
        "Bart Maddux",
        "Shiloh Raulston",
        "Carrie Kimber",
        "Zack Polite",
        "Marni Larson",
        "Justa Spear",
        "Khabib Bint Khuaylid",
        "Obama bin Hasheem",
        "Osama bin Obama bint Ladin",
        "Jimmy Savill",
        "Sahil Justranch",
        "Retard has no name",
        "Woman so doesn't deserve name",
        "Keith Meh Balls",
        "John Marlow Epstein",
        "Son Goku",
        "Eren Yaegar",
        "Mikasa Ackerman",
        "Son Gohan",
        "Annie Louvehart",
        "Wasim bin Heelda",
        "Jennel Garcia",
        "Robin Parth",
        "Kendrick Lamar",
        "Homo Sapien"
    };

    public static string[] occupation =
    {
        "Retard has no job LOL",
        "Certified discord retard",
        "Janitor",
        "Police Officer",
        "Teacher",
        "Cashier",
        "Clerk",
        "Waiter",
        "Waitress",
        "Grocery Bagger",
        "Retailer",
        "Sales-Person",
        "Artist",
        "Singer",
        "Rapper",
        "Trapper",
        "Discord Thug",
        "Gangster",
        "Discord Packer",
        "Mechanic",
        "Carpenter",
        "Electrician",
        "Lawyer",
        "Doctor",
        "Programmer",
        "Software Engineer",
        "Scientist",
        "Gets caught by police",
        "Drug dealer",
        "Mom",
        "Anime animator"
    };

    public static string[] religion =
    {
        "Christian",
        "Muslim",
        "Atheist",
        "Hindu",
        "Buddhist",
        "Jewish",
        "Pagan"
    };

    public static string[] sexuality =
    {
        "Male",
        "Female",
        "Bigender",
        "Transgender",
        "Agender",
        "Shreksexual",
        "Intergender",
        "Bigpeepee",
        "Attack Helicopter",
        "Pansexual",
        "Genderqueer",
        "Third Gender",
        "Soyboy",
        "Keychain",
        "Travesti n-b",
        "Epicene",
        "Demigirl",
        "Demiboy",
        "O",
        "Androgyne",
        "Church Map Icon",
        "Femme",
        "Butch",
        "Xbox User",
        "African American",
        "Genderfluid (female & male)",
        "Toxic-ass shithead",
        "Poligender",
        "Mayonnaise",
        "Special Snowflake",
        "Genderfluid (intergender & neutrois)",
        "Pedophile",
        "Bi-Mayonnaise",
        "Aliagender",
        "Redditard",
        "Commie",
        "Uranus",
        "USB",
        "Neutrois",
        "Bigender: with demigirl",
        "Compwete fookie wetawd uwu (Furry)",
        "John Doe",
        "Cancer",
        "Genderfluid (Demigirl & Third Gender)",
        "Genderfluid (Adrogune & Female)",
        "Bigender (Adrogyne & Neutrois)",
        "Demiagender (with Third gender)",
        "Bowling Balll",
        "Crop Circles",
        "Coom Demon",
        "Mercury",
        "Illuminati",
        "Men that pee without aiming",
        "Chair",
        "Mayonnaise on Chair",
        "Eldritch abomination",
        "Bold & Brash",
        "Cool Kid",
        "a Turn-Off",
        "Pastafarian",
        "Mr.Wordwide",
        "Meteorite",
        "The Man Behind the Slaughter",
        "Bi-Mayonnaise on  Chair",
        "Mike Wazowski",
        "Weed",
        "Traffic Light",
        "Eggman",
        "Eggwoman",
        "Monke",
        "Philosopher' stone",
        "Fourth Gender"
    };
}